blank_issues_enabled: false
contact_links:
  - name: 🤔 Help & Questions
    url: https://community.auth0.com/c/sdks/5
    about: Ask general support or usage questions in the Auth0 Community forums
  - name: 📖 Deploy CLI Documentation
    url: https://github.com/auth0/auth0-deploy-cli#documentation
    about: Check the Deploy CLI documentation for in-depth overview of all the available commands
