name: 🐛 Report a bug
description: Have you found a bug or issue? Create a bug report for this tool
labels: [ "bug" ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: markdown
    attributes:
      value: |
        **Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/responsible-disclosure-policy) details the procedure for disclosing security issues.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
          required: true
        - label: I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
          required: true
        - label: I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
          required: true
        - label: I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
          required: true
        - label: I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
          required: true
        - label: I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expectation
      description: Tell us about the behavior you expected to see.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Detail the steps taken to reproduce this error and, ideally, share a repo of a minimal reproducible example. State whether this issue can be reproduced consistently or if it is intermittent.
      placeholder: |
        1. Given...
        2. When...
        3. Then...
    validations:
      required: true

  - type: input
    id: environment-deploy-cli-version
    attributes:
      label: Deploy CLI version
    validations:
      required: true

  - type: input
    id: environment-node-version
    attributes:
      label: Node version
    validations:
      required: true
