# Auth0-Deploy-CLI Tenant YAML Configuration

tenant:
  # Any tenant settings can go here https://auth0.com/docs/api/management/v2#!/Tenants/get_settings
  friendly_name: 'Auth0 Deploy Example'

pages:
  - name: "login"
    html: "pages/login.html"

  - name: "password_reset"
    html: "pages/password_reset.html"

  - name: "guardian_multifactor"
    html: "pages/guardian_multifactor.html"
    enabled: false

  - name: "error_page"
    html: "pages/error_page.html"


clients:
  -
    name: "My SPA"
    app_type: "spa"
    # Add other client settings https://auth0.com/docs/api/management/v2#!/Clients/post_clients
  -
    name: "My M2M"
    app_type: "non_interactive"
    # Add other client settings https://auth0.com/docs/api/management/v2#!/Clients/post_clients
  -
    name: "My Native app"
    app_type: native
    mobile:
      android:
        app_package_name: com.my.android.id
    native_social_login:
      google:
        enabled: true
    # Add other client settings https://auth0.com/docs/api/management/v2#!/Clients/post_clients

databases:
  - name: "users"
    enabled_clients:
      - "My SPA"
    options:
      enabledDatabaseCustomization: true
      customScripts:
        login: "databases/users/login.js"
        create: "databases/users/create.js"
        delete: "databases/users/delete.js"
        get_user: "databases/users/get_user.js"
        change_email: "databases/users/change_email.js"
        change_password: "databases/users/change_password.js"
        verify: "databases/users/verify.js"

connections:
  - name: "myad-waad"
    strategy: "waad"
    enabled_clients:
      - "My SPA"
    options:
      tenant_domain: 'office.com'
      client_id: 'some_client_id'
      client_secret: 'some_client_secret'
      domain: 'office.com'
      waad_protocol: 'openid-connect'
      api_enable_users: true
      basic_profile: true
      ext_profile: true
      ext_groups: true
    # Add other connection settings (https://auth0.com/docs/api/management/v2#!/Connections/post_connections)


resourceServers:
  -
    name: "My API"
    identifier: "https://##ENV##.myapp.com/api/v1"
    scopes:
      - value: "update:account"
        description: "update account"
      - value: "read:account"
        description: "read account"
    # Add other resource server settings (https://auth0.com/docs/api/management/v2#!/Resource_Servers/post_resource_servers)


emailProvider:
  name: "smtp"
  enabled: true
  credentials:
    smtp_host: "smtp.mailtrap.io"
    smtp_port: 2525
    smtp_user: "smtp_user"
    smtp_pass: "smtp_secret_password"


emailTemplates:
  - template: "verify_email"
    enabled: true
    syntax: "liquid"
    from: "test@email.com"
    subject: "something"
    body: "emails/change_email.html"

  - template: "welcome_email"
    enabled: true
    syntax: "liquid"
    from: "test@email.com"
    subject: "something"
    body: "emails/change_email.html"

  - template: "reset_email_by_code"
    enabled: true
    syntax: "liquid"
    from: "test@email.com"
    subject: "something"
    body: "emails/change_email.html"


clientGrants:
  - client_id: "My M2M"
    audience: "https://##ENV##.myapp.com/api/v1"
    scope:
      - "update:account"


guardianFactors:
  - name: sms
    enabled: true
  - name: push-notification
    enabled: true
  - name: otp
    enabled: true
  - name: email
    enabled: false
  - name: duo
    enabled: false

guardianFactorProviders:
  - name: sms
    provider: twilio
    auth_token: "some_token"
    sid: "some_sid"
    messaging_service_sid: "some_message_sid"

guardianFactorTemplates:
  - name: sms
    enrollment_message: >-
      {{code}} is your verification code for {{tenant.friendly_name}}. Please
      enter this code to verify your enrollment.
    verification_message: '{{code}} is your verification code for {{tenant.friendly_name}}'

guardianPhoneFactorMessageTypes:
  message_types:
    - sms
    - voice

guardianPhoneFactorSelectedProvider:
  provider: twilio

guardianPolicies:
  policies:
    - all-applications

roles:
  - name: Admin
    description: App Admin
    permissions:
      - permission_name: 'update:account'
        resource_server_identifier: 'https://##ENV##.myapp.com/api/v1'
      - permission_name: 'read:account'
        resource_server_identifier: 'https://##ENV##.myapp.com/api/v1'
  - name: User
    description: App User
    permissions:
      - permission_name: 'read:account'
        resource_server_identifier: 'https://##ENV##.myapp.com/api/v1'

actions:
  - name: action-example
    code: ./actions/action-example/code.js
    dependencies:
      - name: lodash
        version: 4.17.21
    deployed: true
    secrets:
      - name: MY_SECRET
        value: _VALUE_NOT_SHOWN_
    status: built
    supported_triggers:
      - id: post-login
        version: v1

triggers:
  credentials-exchange: []
  post-change-password: []
  post-login:
    - action_name: action-example
      display_name: action-example-display-name
  post-user-registration: []
  pre-user-registration: []
  send-phone-message: []

prompts:
  customText:
    en:
      login-id:
        login-id:
          invalid-email-format: Email is not valid.
  enable_ulp_wcag_compliance: false
  identifier_first: false
  partials: {}
  screenRenderers:
    - signup-id:
        signup-id: ./prompts/screenRenderSettings/signup-id_signup-id.json
    - login-passwordless:
        login-passwordless-email-code: ./prompts/screenRenderSettings/login-passwordless_login-passwordless-email-code.json
        login-passwordless-sms-otp: ./prompts/screenRenderSettings/login-passwordless_login-passwordless-sms-otp.json

selfServiceProfiles:
  - name: self-service profile 1
    allowed_strategies:
      - google-apps
      - keycloak-samlp
      - okta
    branding:
      colors:
        primary: '#19aecc'
    customText:
      en:
        get-started:
          introduction: >-
            Welcome! With <p>only a few steps</p> you'll be able to setup.
    description:  self-Service  profile 1
    user_attributes:
      - name: email
        description: Email of the User
        is_optional: false
      - name: name
        description: Name of the User
        is_optional: true
